### ISSUE TITLE
[HELP] command permissions

### ISSUE THREAD

**Issue by kingpin24** [NamVr/DiscordBot-Template#14]
How can you set role permissions for command usage? I'm not able to find it in the example ones except for ownerOnly

thanks

**Comment by NamVr** [comment]
Please briefly describe the issue.
Is it a legacy based command or slash command?

**Comment by kingpin24** [comment]
legacy command, i want to make it so that in the command file, certain roles can be specified such that only those roles can use the command

**Comment by NamVr** [comment]
I'm sorry for the late reply (didn't got notified on your reply).
So you want a command property to check specific roles, or you want to check roles for just a single command inside the command code itself?

Sorry for making it complicated, first of all - it is possible with no doubts. But if you are doing it, then your command may crash on other servers since a role ID can be only of a single server (if you get what I mean)

**Comment by NamVr** [comment]
So if I understand, your bot is a specific server bot for just one server, then making a command property will be pog for less code complications.
I'll give you a hint to get started - Go to events/messageCreate.js and like other command property definition and codes, make your own property. You can take infinite hints from the rest of the code. Good luck!

**Comment by NamVr** [comment]
Reach me out on discord support server for faster communication, links in issue tab - discord.
If you need any more help, let me know. Meanwhile I'll close the issue.
