### ISSUE TITLE
[BUG] Slash commands are not loading.

### ISSUE THREAD

**Issue by ukcai696969** [NamVr/DiscordBot-Template#23]
slash commands not loading

**Comment by NamVr** [comment]
Hi, we need a detailed brief information about your file structure so I can help.

**Comment by ukcai696969** [comment]
hi, what do you mean file structure i just cloned the bot filled in config file and add the bot do my server with bot and application.commands and still ng

**Comment by NamVr** [comment]
I need you to describe what is wrong, since the template has been tested with thousand of clones, and we're pretty sure nothing is wrong from our side.

What do you mean by slash commands are not loading? Are they not loading in the bot console, or the api? Or it doesn't work globally and it works in your dev server only? There are many possibilities. Have you enabled intents properly? Have you ensured properly permissions of your bot in that server? Has the server disabled your bot's commands?

**Comment by ukcai696969** [comment]
yes they are loading in the console and everything the bot has intents and perms

**Comment by ukcai696969** [comment]
i have ive tried evrything still no

**Comment by NamVr** [comment]
Well then, you will have to share us your codebase so we can check what's wrong. Otherwise, we can't help you.
