### ISSUE TITLE
Add Mongo Support 

### ISSUE THREAD

**Issue by BigglesDevs** [NamVr/DiscordBot-Template#26]
**Suggestion**
Not a bug, Maybe add mongo support to the template or please describe how i can  do it.

**Comment by NamVr** [comment]
Please note that labeling an issue as a "bug" doesn't make any urgency and I do not encourage to misuse labels just to get attention, you have clearly mentioned "not a bug" but still labelled it as "bug".

Now to your question, the template does support any kind of databases you have to get it from NPM. We are not going to add support for mongo in our template since the template is free of any external dependencies. 
However, you can check out this link to get started: https://www.npmjs.com/package/mongoose
